# Algebra lineal

In [1]:
import numpy as np

## 2 tipos de objetos se pueden usar como matrices

In [2]:
A_arr = np.array([[3.,  2., 0.],
                  [1., -1., 0.],
                  [0.,  5., 1.]])

A_mat = np.matrix([[3.,  2., 0.],
                   [1., -1., 0.],
                   [0.,  5., 1.]])

print(type(A_arr))
print(type(A_mat))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


## Invertir matriz

In [3]:
from scipy.linalg import inv

print(inv(A_arr))
print(inv(A_mat))

[[ 2.00000000e-01  4.00000000e-01  1.85037171e-18]
 [ 2.00000000e-01 -6.00000000e-01 -7.40148683e-18]
 [-1.00000000e+00  3.00000000e+00  1.00000000e+00]]
[[ 2.00000000e-01  4.00000000e-01  1.85037171e-18]
 [ 2.00000000e-01 -6.00000000e-01 -7.40148683e-18]
 [-1.00000000e+00  3.00000000e+00  1.00000000e+00]]


## Truco para formatear como se ve una matriz

In [4]:
inv_A = inv(A_mat)
print(np.array2string(inv_A, formatter={'float_kind':'{0:-5.2f}'.format}))

[[ 0.20  0.40  0.00]
 [ 0.20 -0.60 -0.00]
 [-1.00  3.00  1.00]]


## Resolver un sistema vs. invertir una matriz

$A \vec{x} = \vec{b}$

In [5]:
b_arr = np.array([2, 4, -1])
b_mat = np.matrix([[2], [4], [-1]])

In [6]:
inv(A_mat) * b_mat

matrix([[ 2.],
        [-2.],
        [ 9.]])

In [7]:
inv(A_arr) @ b_arr

array([ 2., -2.,  9.])

In [8]:
np.dot(inv(A_arr), b_arr)

array([ 2., -2.,  9.])

In [9]:
from scipy.linalg import solve

solve(A_mat, b_mat)

array([[ 2.],
       [-2.],
       [ 9.]])

In [10]:
solve(A_arr, b_arr)

array([ 2., -2.,  9.])

# Descomposición PLU

In [11]:
from scipy.linalg import lu

In [12]:
help(lu)

Help on function lu in module scipy.linalg.decomp_lu:

lu(a, permute_l=False, overwrite_a=False, check_finite=True)
    Compute pivoted LU decomposition of a matrix.
    
    The decomposition is::
    
        A = P L U
    
    where P is a permutation matrix, L lower triangular with unit
    diagonal elements, and U upper triangular.
    
    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L  (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    
    Returns
    -------
    **(If permute_l == False)**
    
    p : (M, M) ndarray
        Permutation matr

In [13]:
p, l, u = lu(A_mat)

In [14]:
print(type(p))

<class 'numpy.ndarray'>


In [15]:
print(p)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [16]:
print('L =')
print(np.array2string(l, formatter={'float_kind':'{0:-5.2f}'.format}))
print('')
print('U =')
print(np.array2string(u, formatter={'float_kind':'{0:-5.2f}'.format}))

L =
[[ 1.00  0.00  0.00]
 [ 0.00  1.00  0.00]
 [ 0.33 -0.33  1.00]]

U =
[[ 3.00  2.00  0.00]
 [ 0.00  5.00  1.00]
 [ 0.00  0.00  0.33]]


In [17]:
print(p @ l @ u)

[[ 3.  2.  0.]
 [ 1. -1.  0.]
 [ 0.  5.  1.]]


## Métodos optimizados para resolver sistemas de ecuaciones.

$A \vec{x} = L U \vec{x} = \vec{b}$

$L \vec{y} = \vec{b}$

$U \vec{x} = \vec{y}$

In [18]:
from scipy.linalg import solve_triangular

y = solve_triangular(l, p @ b_mat, lower=True)
print(y)

[[ 2.]
 [-1.]
 [ 3.]]


In [19]:
x = solve_triangular(u, y, lower=False)
print(x)

[[ 2.]
 [-2.]
 [ 9.]]
